name: Deployment Dispatcher

on:
  workflow_dispatch:

jobs:
  pypi-package-stats-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            curl --request POST \
            --url "https://api.github.com/repos/ivdatahub/pypi-package-stats/dispatches" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer $GH_TOKEN" \
            --data '{"event_type": "workflow_trigger", "client_payload": {"repository": "${{ github.repository }}"}}'
