name: Deployment Dispatcher

on:
  workflow_dispatch:

jobs:
  notify-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ {{ secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ivdatahub/pypi-package-stats/dispatches \
            -d '{"event_type": "workflow_trigger", "client_payload": {"repository": "${{ github.repository }}"}}'
