name: Deployment Dispatcher

on:
  workflow_dispatch:

jobs:
  pypi-package-stats-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/repos/ivdatahub/pypi-package-stats/dispatches \
          -d '{"event_type": "workflow_trigger", "client_payload": {"repository": "${{ github.repository }}"}}'
