name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  notify-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ivdatahub/pypi-package-stats/dispatches \
            -d '{"event_type": "workflow_trigger", "client_payload": {"repository": "${{ github.repository }}"}}'
